version: '3.5'

services:

  koha-db:
    container_name: koha-db
    image: mariadb:10.6
    restart: always
    volumes:
      - koha-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: koha

  koha:
    container_name: koha
    #image: ghcr.io/brittos/koha-docker/koha:latest
    image: koha
    #build: ./koha
    restart: always
    volumes:
      - koha:/var/lib/koha/
      - koha-sites:/etc/koha/
      - koha-apache:/etc/apache2/
    cap_add:
        - SYS_NICE
        - DAC_READ_SEARCH
    depends_on:
        - koha-db
    environment:
      LIBRARY_NAME: test
      DOMAIN: localhost
      SLEEP: 3
      INTRAPORT: 8080
      OPACPORT: 8081
      DB_HOST: koha-db
      DB_ROOT_PASSWORD: koha
      MASTER_PASSWORD: koha123
      KOHA_TRANSLATE_LANGUAGES: "pt-BR"
    ports:
      - "8081:8081"
      - "8080:8080"

volumes:
  koha-db:
  koha:
  koha-sites:
  koha-apache:
